apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  replicas: 2
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          image: odoo
          ports:
            - containerPort: 8069
              name: odoo
          env:
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: HOST
              value: "postgresql"
          volumeMounts:
            - name: volume
              mountPath: /var/lib/odoo
      volumes:
        - name: volume
