name: Kubernetes Cluster
on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          kubectl: "1.17.1"

      - run: |
          kubectl version --client
          kubectl get all --all-namespaces

      # - name: Setup Minikube
      #   uses: manusa/actions-setup-minikube@v2.7.1
      #   with:
      #     minikube version: "v1.26.1"
      #     kubernetes version: "v1.25.0"
      #     github token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Interact with the cluster
      #   run: |
      #     kubectl get node
      #     kubectl get all --all-namespaces

      # - uses: engineerd/setup-kind@v0.5.0
      #   with:
      #     version: "v0.11.1"

      # - name: Test
      #   run: |
      #     kubectl cluster-info
      #     kubectl get pods --all-namespaces
      #     kubectl get all
      #     echo "current-context:" $(kubectl config current-context)
      #     echo "environment-kubeconfig:" ${KUBECONFIG}
