name: Kubernetes Deploy
on: push
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/my-app container=${{ toJSON(github.repository) }}:${{ toJSON(github.sha) }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.25.0 # specify kubectl binary version explicitly
          command: rollout status deployment/my-app
# /////////////////////////////////////////////
# name: Kubernetes Deploy
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: deploy to cluster
#         uses: steebchen/kubectl@v2.0.0
#         with: # defaults to latest kubectl binary version
#           config: ${{ secrets.KUBE_CONFIG_DATA }}
#           command: set image deployment/my-app container=${{ github.repository }}:${{ github.sha }}

#       - name: verify deployment
#         uses: steebchen/kubectl@v2.0.0
#         with:
#           config: ${{ secrets.KUBE_CONFIG_DATA }}
#           version: v1.25.2 # specify kubectl binary version explicitly
#           command: rollout status deployment/my-app

# name: Deploy
# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#   runs-on: ubuntu-latest

#   steps:
#     - name: Get Code
#       uses: actions/checkout@v3
#     - name: Deploy to cluster
#       uses: myrotvorets/kubectl-action@2.0.0
#       with:
#         config: ${{ secrets.KUBE_CONFIG_DATA }}
#         version: latest
#         args: set image --record deployment/application container=${{ github.repository }}:${{ github.sha }}
#     - name: Verify deployment
#       uses: myrotvorets/kubectl-action@2.0.0
#       with:
#         config: ${{ secrets.KUBE_CONFIG_DATA }}
#         version: latest
#         args: rollout status deployment/application
