name: Kubernetes Minikube Cluster
on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Deploy to minikube
        run: |
          kubectl apply -f postgresql.yaml
          kubectl apply -f dbservice.yaml
          kubectl apply -f odoo.yaml
          kubectl apply -f odooservice.yaml
          kubectl apply -f CronJob.yaml

      - name: Test Deployment
        run: |
          kubectl version --client
          kubectl get all -A
